export const CREATE_USER_WITH_E_MAIL: string = 'CREATE_USER_WITH_E_MAIL';
export const CREATE_USER_WITH_E_MAIL_SUCCEEDED: string = 'CREATE_USER_WITH_E_MAIL_SUCCEEDED';
export const CREATE_USER_WITH_E_MAIL_FAILED: string = 'CREATE_USER_WITH_E_MAIL_FAILED';

export const SIGN_IN_WITH_E_MAIL: string = 'SIGN_IN_WITH_E_MAIL';
export const SIGN_IN_WITH_E_MAIL_SUCCEEDED: string = 'SIGN_IN_WITH_E_MAIL_SUCCEEDED';
export const SIGN_IN_WITH_E_MAIL_FAILED: string = 'SIGN_IN_WITH_E_MAIL_FAILED';